// wxui/vapp/src/app-layouts/app.vue
<template>
    
    <header :ref="el => app.headerEle.value = el" class="bg-white border-b border-gray-200 flex items-center px-1 shadow-sm z-30">
      <div class="flex items-center space-x-3">
        <!-- Burger icon -->
        <button
            @click="app.toggleSidebar"
             class="w-8 h-8 flex items-center justify-center cursor-pointer hover:bg-gray-100 rounded transition"
        >
         <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
           <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                 d="M4 6h16M4 12h16M4 18h16"/>
         </svg>
       </button>

        <span class="text-sm font-medium hidden sm:inline text-gray-700">My App</span>
      </div>
    </header>
    <aside
  :ref="el => app.sideBarEle.value = el"
  class="sidebar debug2"
 :class="{ 'translate-x-0': app.sidebarOpen }"
>
    <slot name="sidebar">
            
        </slot>
    </aside>
    
    <div class="flex flex-col debug " :ref="ele=>app.bodyEle.value=ele">
        <slot name="body">
            body

        </slot>
    </div>
   
</template>
<script lang="ts" setup>
import libs from '@core/lib';
class AppLayout extends libs.BaseUI {
    headerEle = libs.newDOMRef();
    bodyEle = libs.newDOMRef();
    sideBarEle = libs.newDOMRef();
    sidebarOpen = libs.newRef(true);
    onInit(): void {
       
        this.fixBodySize();
        this.fixSiderBar();
        const self=this;
        debugger;
        window.addEventListener("resize",()=>{
            self.fixBodySize();
        });
        this.hideSideBarWhenMouseMoveOnBody();
    }
    hideSideBarWhenMouseMoveOnBody() {
        const self=this;
        this.bodyEle.value.addEventListener("mousemove",()=>{
            if (self.isSideBarOpen()){
                self.toggleSidebar();
            }
           
        })
    }
    isSideBarOpen() {
        const sideBar = this.sideBarEle?.value;
        return sideBar.style.transform === 'translateX(0px)';
    }
    /*
        this funx will make position of sideBar top is height of header
        bottom is bottom of body
    */
    fixSiderBar() {
        const header = this.headerEle?.value;
        const sideBar = this.sideBarEle?.value;
        const body = this.bodyEle?.value;

        if (!header || !sideBar || !body) return;

        // Lấy chiều cao header
        const headerHeight = header.offsetHeight;

        // Lấy chiều cao body (viewport - header)
        const bodyRect = body.getBoundingClientRect();
        const top = headerHeight; // vị trí top
        const bottom = window.innerHeight - bodyRect.bottom; // khoảng cách tới bottom

        // Gán style cho sidebar
        sideBar.style.position = 'fixed';
        sideBar.style.top = `${top}px`;
        sideBar.style.bottom = `${0}px`;
        sideBar.style.overflowY='auto';
        //sideBar.style.height = `${bottom-top-8}px`;
    }
    /*
        this function will fix this.bodyEle.value: HTMLElement
        by make height of this.bodyEle.value= height of window- this.header.value.height
        and this.bodyEle.value.width= window.innerWidth
    */
    fixBodySize() {
        const header = this.headerEle?.value;
        const body = this.bodyEle?.value;

        if (!header || !body) return;

        const headerHeight = header.getBoundingClientRect().height;

        body.style.height = (window.innerHeight - headerHeight) + "px";
        body.style.width = window.innerWidth + "px";
        
    }
    toggleSidebar() {
        const sideBar = this.sideBarEle?.value;
    if (!sideBar) return;

    const isOpen = sideBar.style.transform === 'translateX(0px)';
    sideBar.style.transform = isOpen ? 'translateX(-100%)' : 'translateX(0)';
        
    }
}
const app=new AppLayout();
</script>
<style scoped>
.sidebar {
  transform: translateX(-100%);
  transition: transform 0.3s ease-in-out;
}
.sidebar.open {
  transform: translateX(0);
}
.debug2 {
    border: solid 4px blue;
}
</style>

// wxui/xapp/src/template-layout/app.svelte
<!-- src/lib/components/Layout.svelte -->
<script lang="ts">
    import { BaseUi } from "@core/core";
    class Layout extends BaseUi {
        headerEl: HTMLElement | undefined;
        sidebarEl: HTMLElement | undefined;
        bodyEl: HTMLElement | undefined;
        burgerEl: HTMLElement | undefined;
        isSidebarOpen: boolean | undefined;
        screen: HTMLElement | undefined;
        self: Layout | undefined;
        slotBody: HTMLElement | undefined;
        onBugerClick() {}
        async onInit() {
            if (this.screen) {
                this.slotBody = await this.findBySlotName(this.screen, "body");
                this.fixBodySize();
                const self = this; // Lưu lại this

                window.addEventListener("resize", () => {
                    self.fixBodySize();
                });
            }

            this.isntallBugerEvent();
        }
        /**
         * Adjusts the height of the body slot to fit the viewport minus the header height.
         * Uses `this.slotBody` and `this.headerEl` which are assumed to be bound HTMLElement references.
         */
        fixBodySize() {
            // Get references (already bound via bind:this in Svelte)
            const slotBody = this.slotBody;
            const headerEl = this.headerEl;

            // Skip if elements are not available
            if (!slotBody || !headerEl) {
                console.warn("[fixBodySize] Missing slotBody or headerEl");
                return;
            }

            // Get header height (including padding, border, margin)
            const headerHeight = headerEl.offsetHeight;

            // Get viewport height (full browser window height)
            const viewportHeight = window.innerHeight;

            // Calculate and set body height
            const bodyHeight = viewportHeight - headerHeight;
            slotBody.style.height = `${bodyHeight}px`;
            slotBody.style.width = `${window.innerWidth}px`;
            // Optional: Ensure content doesn't overflow
            slotBody.style.overflow = "auto";

            // Debug log
            console.log(
                `[fixBodySize] Header: ${headerHeight}px | Viewport: ${viewportHeight}px | Body: ${bodyHeight}px`,
            );
        }
        isntallBugerEvent() {
            // if (!this.burgerEl) return;
            // (this.burgerEl as any).addEventListener(
            //     "click",
            //     this.toggleSidebar,
            // );
        }

        toggleSidebar() {
            const self = this;
            console.log(this);
            function hideSideBar() {
                self.isSidebarOpen = false;
                self.sidebarEl?.classList.remove("translate-x-0");
                self.sidebarEl?.classList.add("-translate-x-full");
            }
            if (!this.sidebarEl) return;
            this.isSidebarOpen = !this.isSidebarOpen;
            if (this.isSidebarOpen) {
                this.sidebarEl.classList.remove("-translate-x-full");
                this.sidebarEl.classList.add("translate-x-0");
                this.slotBody?.addEventListener("mousemove", hideSideBar);
            } else {
                this.sidebarEl.classList.remove("translate-x-0");
                this.sidebarEl.classList.add("-translate-x-full");
                this.slotBody?.removeEventListener("mousemove", hideSideBar);
            }
        }
    }
    const layout = new Layout();
</script>

<div
    class="main min-h-screen flex flex-col bg-gray-50"
    bind:this={layout.screen}
>
    <!-- Header -->
    <header
        bind:this={layout.headerEl}
        class="h-11 bg-white border-b border-gray-200 flex items-center px-4 shadow-sm z-30"
    >
        <div class="flex items-center space-x-3">
            <!-- Burger icon (chỉ để hiển thị, không emit) -->
            <div
                bind:this={layout.burgerEl}
                on:click={() => {
                    layout.toggleSidebar();
                }}
                class="w-6 h-6 flex items-center justify-center cursor-pointer hover:bg-gray-100 rounded"
            >
                <svg
                    class="w-5 h-5 text-gray-600"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                >
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M4 6h16M4 12h16M4 18h16"
                    />
                </svg>
            </div>
            <span class="text-sm font-medium hidden sm:inline text-gray-700"
                >My App</span
            >
        </div>
    </header>

    <!-- Main content area -->
    <div class="flex flex-1 relative shadow-lg rounded-xl">
        <!-- Sidebar -->
        <aside
            bind:this={layout.sidebarEl}
            style="position: fixed; top: 44px; height: calc(100vh - 44px);"
            class="sidebar w-64 bg-white border-r border-gray-200 z-20 transition-transform duration-300 ease-in-out -translate-x-full"
            class:open={false}
        >
            <div class="p-4">
                <slot name="sidebar">
                    <p class="text-gray-500 italic">Default Sidebar</p>
                </slot>
            </div>
        </aside>
        <slot name="body" class="debug">
            <div class="p-6">
                <p class="text-gray-500 italic">Default Body Content</p>
            </div>
        </slot>
        <!-- Body -->
        <!-- <main class="flex-1 pt-1 pl-0 md:pl-64 transition-all duration-300">
           
        </main> -->
    </div>
</div>

<style>
    /* Sidebar mở (nếu sau này bật) */
    .sidebar.open {
        transform: translateX(0);
    }
    .sidebar {
        transform: translateX(-100%);
    }
    @media (min-width: 768px) {
        .sidebar {
            transform: translateX(0) !important;
        }
    }
    .-translate-x-full {
        transform: translateX(-100%);
    }
</style>
