// wxui/vapp/src/views/auth/login.vue
<template>
    <div class="h-full  flex items-center justify-center">
      <div class="bg-white rounded-2xl shadow-2xl p-10 w-full max-w-md widget-container border-gray-600">
        <!-- Header -->
        <h2 class="text-3xl font-bold text-center text-gray-800 mb-6">Sign In</h2>
        
        <!-- Form -->
        <div class="space-y-4">
          <div>
            <label class="block text-gray-700 mb-1" for="username">Username</label>
            <input
              type="text"
              id="username"
              placeholder="Your username"
              v-model="login.data.username"
              class="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-indigo-400 focus:outline-none"
            />
          </div>
          <div>
            <label class="block text-gray-700 mb-1" for="password">Password</label>
            <input
              type="password"
              id="password"
              placeholder="********"
              v-model="login.data.password"
              class="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-indigo-400 focus:outline-none"
            />
          </div>
          <button
            @click="login.doLogin"
            class="w-full py-2 bg-indigo-600 text-white font-semibold rounded-lg shadow hover:bg-indigo-700 transition"
          >
            Sign In
          </button>
        </div>
        <p class="mt-6 text-center text-gray-500 text-sm">
           {{ login.errMsg }}
        </p>
        <!-- Footer -->
        <p class="mt-6 text-center text-gray-500 text-sm">
          Forgot your password? <a href="#" class="text-indigo-600 hover:underline">Reset</a>
        </p>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
    import libs from '@core/lib';

   class Login extends libs.BaseUI{
      data ={
        username:"",
        password:""
      }
      errMsg=libs.newRef(null);
      private _onAfterLogin=undefined;
      async doLogin() {
         let res= await libs.login(this.data.username,this.data.password);
         if (res.error) {
            this.errMsg=res.error;
            
         } else {
            libs.sessionStore.set("tk",res.access_token);
            await this.raiseAfterLogin();
            
         }
         
      }
     async raiseAfterLogin() {
       if(this._onAfterLogin){
          await this._onAfterLogin();
       }
     }
     onAfterLogin(fn:()=>{}){
        this._onAfterLogin=fn;
     }
    
   }
   const instance= new Login();

   const login=libs.newReactive(instance) ;
   function getIns() {
    return instance;
   }
   defineExpose({
    instance
   })
  </script>

// wxui/xapp/src/views/auth/login.svelte
<script lang="ts">
    import { BaseUi } from "@core/core";
    import LoginLayout from "@template-layout/LoginLayout.svelte";
    const test = () => {
        alert("OK");
    };
    class Login extends BaseUi {
        data = $state({
            username: "",
            password: "",
            error: "",
        });
        _afterLogin: (() => void) | undefined;
        constructor() {
            super();
        }
        async doLogin() {
            try {
                let ret = await this.app.loginAsync(
                    this.data.username,
                    this.data.password,
                );

                if (ret.error) {
                    this.data.error = "Login fail";
                } else {
                    this.app.setSessionValue("tk", ret.access_token);
                    if (this._afterLogin) {
                        this._afterLogin();
                    }
                }
            } catch (error) {
                this.data.error = "Login fail";
            }
        }
        afterLogin(fn: () => void) {
            this._afterLogin = fn;
        }
    }
    const login = new Login(); // lam sao tra ve cai nay sau khi goi ham renderDynamicComponent
</script>

<div bind:this={login.Element} class="flex-1 w-full h-full overflow-hidden">
    <LoginLayout>
        <input
            slot="username-input"
            bind:value={login.data.username}
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
        />
        <input
            type="password"
            slot="password-input"
            bind:value={login.data.password}
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500"
        />
        <button
            slot="submit-button"
            on:click={() => login.doLogin()}
            class="w-full py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl font-semibold hover:shadow-lg transform hover:scale-105 transition-all duration-200 flex items-center justify-center gap-2"
        >
            Sign In
        </button>
        <div
            slot="error-message"
            class="text-red-600 text-sm font-medium animate-fade-in"
        >
            {login.data.error}
        </div>
    </LoginLayout>
</div>
