// hrm/src/routes/login/+page.svelte
<script>
	let username = '';
	let password = '';
	let error = '';

	function handleLogin() {
		if (username === 'admin' && password === '123456') {
			alert('Đăng nhập thành công ✅');
			// ở thực tế thì redirect về dashboard
			window.location.href = '/dashboard';
		} else {
			error = 'Sai email hoặc mật khẩu!';
		}
	}
</script>

<div class="flex items-center justify-center min-h-screen bg-gray-100">
	<div class="w-full max-w-md bg-white rounded-2xl shadow-lg p-8">
		<h1 class="text-2xl font-bold text-center text-gray-800 mb-6">Đăng nhập</h1>

		{#if error}
			<p class="text-red-600 text-sm mb-4">{error}</p>
		{/if}

		<form on:submit|preventDefault={handleLogin} class="space-y-4">
			<div>
				<label class="block text-sm font-medium text-gray-700">Username</label>
				<input
					type="text"
					bind:value={username}
					placeholder="Your username"
					class="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
					required
				/>
			</div>

			<div>
				<label class="block text-sm font-medium text-gray-700">Mật khẩu</label>
				<input
					type="password"
					bind:value={password}
					placeholder="••••••••"
					class="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
					required
				/>
			</div>

			<button
				type="submit"
				class="w-full bg-blue-600 text-white font-semibold py-2 rounded-lg hover:bg-blue-700 transition"
			>
				Đăng nhập
			</button>
		</form>

		<p class="mt-6 text-center text-sm text-gray-600">
			Chưa có tài khoản?
			<a href="/register" class="text-blue-600 hover:underline">Đăng ký</a>
		</p>
	</div>
</div>

// wxui/vapp/src/views/auth/login.vue
<template>
    <div class="h-full  flex items-center justify-center">
      <div class="bg-white rounded-2xl shadow-2xl p-10 w-full max-w-md widget-container border-gray-600">
        <!-- Header -->
        <h2 class="text-3xl font-bold text-center text-gray-800 mb-6">Sign In</h2>
        
        <!-- Form -->
        <div class="space-y-4">
          <div>
            <label class="block text-gray-700 mb-1" for="username">Username</label>
            <input
              type="text"
              id="username"
              placeholder="Your username"
              v-model="login.data.username"
              class="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-indigo-400 focus:outline-none"
            />
          </div>
          <div>
            <label class="block text-gray-700 mb-1" for="password">Password</label>
            <input
              type="password"
              id="password"
              placeholder="********"
              v-model="login.data.password"
              class="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-indigo-400 focus:outline-none"
            />
          </div>
          <button
            @click="login.doLogin"
            class="w-full py-2 bg-indigo-600 text-white font-semibold rounded-lg shadow hover:bg-indigo-700 transition"
          >
            Sign In
          </button>
        </div>
        <p class="mt-6 text-center text-gray-500 text-sm">
           {{ login.errMsg }}
        </p>
        <!-- Footer -->
        <p class="mt-6 text-center text-gray-500 text-sm">
          Forgot your password? <a href="#" class="text-indigo-600 hover:underline">Reset</a>
        </p>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
    import libs from '@core/lib';

   class Login extends libs.BaseUI{
      data ={
        username:"",
        password:""
      }
      errMsg=libs.newRef(null);
      private _onAfterLogin=undefined;
      async doLogin() {
         let res= await libs.login(this.data.username,this.data.password);
         if (res.error) {
            this.errMsg=res.error;
            
         } else {
            libs.sessionStore.set("tk",res.access_token);
            await this.raiseAfterLogin();
            
         }
         
      }
     async raiseAfterLogin() {
       if(this._onAfterLogin){
          await this._onAfterLogin();
       }
     }
     onAfterLogin(fn:()=>{}){
        this._onAfterLogin=fn;
     }
    
   }
   const instance= new Login();

   const login=libs.newReactive(instance) ;
   function getIns() {
    return instance;
   }
   defineExpose({
    instance
   })
  </script>
